### ISSUE TITLE
New customer could not be added by Add Customer Plugin

### ISSUE THREAD

**Issue by ivabizov** [dans-art/wac-woocommerce-add-customer#15]
New customer could not be added by Add Customer Plugin. Please contact the Plugin Author.
This mesage post my wordpress site

**Comment by dans-art** [comment]
Hi Ihor
Thanks for the report.
Do you have the capability to add and edit users?
Also in the Error Log of PHP you will find more information about given arguments. If you could send me the output from the Error log, that would help to determine the issue.
Best, Daniel

**Comment by ivabizov** [comment]
[Mon Oct 24 10:17:27.749641 2022] [php:notice] [pid 30542] [client 172.70.251.29:0] New customer could not be added by Add Customer Plugin. Please contact the Plugin Author. - [{&quot;errors&quot;:{&quot;registration-error-username-exists&quot;:[&quot;\\u0410\\u043a\\u043a\\u0430\\u0443\\u043d\\u0442 \\u0441 \\u0442\\u0430\\u043a\\u0438\\u043c \\u0438\\u043c\\u0435\\u043d\\u0435\\u043c \\u043f\\u043e\\u043b\\u044c\\u0437\\u043e\\u0432\\u0430\\u0442\\u0435\\u043b\\u044f \\u0443\\u0436\\u0435 \\u0437\\u0430\\u0440\\u0435\\u0433\\u0438\\u0441\\u0442\\u0440\\u0438\\u0440\\u043e\\u0432\\u0430\\u043d. \\u041f\\u043e\\u0436\\u0430\\u043b\\u0443\\u0439\\u0441\\u0442\\u0430, \\u0432\\u044b\\u0431\\u0435\\u0440\\u0438\\u0442\\u0435 \\u0434\\u0440\\u0443\\u0433\\u043e\\u0435 \\u0438\\u043c\\u044f.&quot;]},&quot;error_data&quot;:[]},&quot;.&quot;,&quot;andreymyzik1983@gmail.com&quot;], referer: https://bot.the.in.ua/wp-admin/post-new.php?post_type=shop_order

**Comment by dans-art** [comment]
Hi
I checked the issue and created an update with a possible solution.
If you use Cyrillic language, please note, that those characters will be removed, when creating an email or username.
 
There is a workaround to that.
1. Create a custom field in the billing section (Code below)
2. Change the format of the email to [custom_field_1]@your-email.com
3. Set the desired name for the email by using the custom field while creating a new order.

`/**
 * Add a custom Field to the Woocommerce billing section (Backend only!)
 *
 */
add_action('woocommerce_admin_order_data_after_billing_address', function ($order) {
    $value = get_post_meta($order->ID, 'custom_field_1', true); //Loads the value of the custom field
    echo '<div id="wac_add_customer_con" class="edit_address" style="display: none;">'; //The class "edit_address" is important to show the field when the billing details are edited 
    echo  '<label for="custom_field_1">My fancy field</label><br/>'; //Label to display
    echo '<input type="text" name="custom_field_1" id="custom_field_1" value="'.$value.'" placeholder=""/>'; //The Input field
    echo '</div>';
}, 10, 1);

/**
 * Saves the new meta field when the order is saved
 */
add_action('woocommerce_process_shop_order_meta', function($order_id, $posted)
{
    if (isset($_REQUEST['custom_field_1'])) {
        update_post_meta($order_id, 'custom_field_1', $_REQUEST['custom_field_1']);
    }
    return;
}, 99, 2);

/**
 * Registers the custom field to be used as a placeholder
 */

add_filter('wac_supported_fake_email_parts', function (array $fields) {
    $fields[] = 'custom_field_1'; //Name of the custom field to add
    return $fields;
}, 10, 1);
`
Please let me know, if that solved the issue for you.
Best, Daniel

**Comment by ivabizov** [comment]
Perhaps to solve this problem for Cyrillic users, it would be more logical to implement support for a transliteration module, such as Cyr-To-Lat?

**Comment by dans-art** [comment]
Hi
I just released a new update, which should fix the issue with non-Latin characters. 
Otherwise, it is possible to hook in with two new filters to modify the username and email before saving to the database.
Please let me know if the issue is solved.
Best, Daniel

**Comment by ivabizov** [comment]
Everything worked fine, thank you
