### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by hmprintdesign** [dans-art/wac-woocommerce-add-customer#3]
Hello
the plugin creates the customer but not the profile anymore

**Comment by dans-art** [comment]
Hi
Thanks for the report.
Can you provide me some more Information?
- Wordpress Version and Woocommerce Version
- Installed Plugins
- PHP Version

Best, Daniel

**Comment by hmprintdesign** [comment]
Hello Daniel,

WordPress environment
WordPress address (URL):                https://hmprintdesign.com
Site address (URL):             https://hmprintdesign.com
WooCommerce version:            5.4.1
WooCommerce REST API package:            5.4.1 /home3/hmprintd/public_html/wp-content/plugins/woocommerce/includes
WooCommerce Blocks package:              5.1.0 /home3/hmprintd/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler package:                3.1.6 /home3/hmprintd/public_html/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin package:               2.3.1 /home3/hmprintd/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin
Log directory writable:          /home3/hmprintd/public_html/wp-content/uploads/wc-logs/
WordPress version:              5.7.2
WordPress multisite:            –
WordPress memory limit:         2 GB
WordPress debug mode:
WordPress cron:
Language:               en_US
External object cache:          –


Server environment
Server info:            Apache
PHP version:            7.4.20
PHP post max size:              125 MB
PHP time limit:         60
PHP max input vars:             5000
cURL version:           7.77.0, OpenSSL/1.1.1k
SUHOSIN installed:              –
MySQL version:          5.7.23-23
Max upload size:                13 GB
Default timezone is UTC:
fsockopen/cURL:
SoapClient:
DOMDocument:
GZip:
Multibyte string:
Remote post:
Remote get:

Theme
Name:           Storefront HM
Version:                2.5.8.1596586492
Author URL:             https://woocommerce.com/
Child theme:
Parent theme name:              Storefront
Parent theme version:           3.7.0
Parent theme author URL:                https://woocommerce.com/
WooCommerce support:





Active Plugins
Add Customer for WooCommerce            by Dan's Art – 1.0
Akismet Anti-Spam<https://akismet.com/>         by Automattic – 4.1.9
Blog2Social: Social Media Auto Post & Scheduler<https://www.blog2social.com/>           by Blog2Social, Adenion – 6.7.2
Child Theme Configurator<http://www.childthemeconfigurator.com/>                by Lilaea Media – 2.5.8
Code Snippets<https://github.com/sheabunge/code-snippets>               by Code Snippets Pro – 2.14.1
Copy Or Move Comments           by biztechc – 5.0.1
Join.chat<https://join.chat/>           by Creame – 4.1.14
Customer Reviews for WooCommerce<https://wordpress.org/plugins/customer-reviews-woocommerce/>           by CusRev – 4.18
DHWCPage - WooCommerce Page Builder<http://sitesao.com/>                by SiteSao Team – 5.2.18
Envato Market<https://envato.com/market-plugin/>                by Envato – 2.0.6
Flying Pages by WP Speed Matters<https://wordpress.org/plugins/flying-pages/>           by Gijo Varghese – 2.4.2
Google Listings and Ads         by WooCommerce – 1.1.0
Jetpack<https://jetpack.com/>           by Automattic – 9.8.1
Join.chat CTA Extras<https://join.chat/en/addons/cta-extras/>           by Creame – 2.4.0
Join.chat Omnichannel<https://join.chat/en/addons/omnichannel/>         by Creame – 1.2.1
WPBakery Page Builder<http://wpbakery.com/>             by Michael M - WPBakery.com – 6.6.0
Login as User (PRO version)<https://www.web357.com/product/login-as-user-wordpress-plugin>              by Web357 – 1.4.0
MailPoet 3 Premium (New)<http://www.mailpoet.com/>              by MailPoet – 3.64.0
MailPoet 3 (New)<http://www.mailpoet.com/>              by MailPoet – 3.64.2
Perfmatters<https://perfmatters.io/>            by forgemedia – 1.7.4
Shortcode Cleaner<https://plugins.jozoor.com/shortcode-cleaner>         by Jozoor – 1.1.6
Social Login Pro for WooCommerce<https://wppluginexperts.com/>          by WP Plugin Experts – 1.0.1
Storefront Hamburger Menu<https://wordpress.org/plugins/storefront-hamburger-menu/>             by WooCommerce – 1.2.2
Storefront Homepage Contact Section<http://woothemes.com/products/storefront-homepage-contact-section/>         by WooThemes – 1.0.5
Storefront Mega Menus<https://woocommerce.com/products/storefront-mega-menus/>          by WooCommerce – 1.6.2
Storefront Parallax Hero<http://woocommerce.com/products/storefront-parallax-hero/>             by WooCommerce – 1.5.7
Storefront Powerpack<https://woocommerce.com/products/storefront-powerpack/>            by WooCommerce – 1.6.1
Storefront Product Hero<http://woothemes.com/products/storefront-product-hero/>         by WooThemes – 1.2.13
WC Speed Drain Repair<http://wpfixit.com/>              by WP Fix It – 1.3
WooCommerce Cart Abandonment Recovery<https://cartflows.com/>           by CartFlows Inc – 1.2.12
WooCommerce Estimated Shipping Date             by Mohammed Saimon – 4.2.0
Product Feed PRO for WooCommerce<https://www.adtribes.io/support/?utm_source=wpadmin&utm_medium=plugin&utm_campaign=woosea_product_feed_pro>            by AdTribes.io – 10.3.9
WooCommerce Advanced Bulk Edit<https://wpmelon.com/>            by George Iron – 4.6.2.3
WooCommerce Etsy Importer<https://omniwp.com/apps/woocommerce-etsy-importer/>           by omniWP – 3.9.97
Etsy Integration for WooCommerce<https://cedcommerce.com/>              by CedCommerce – 2.0.4
WooCommerce File Approval               by Lagudi Domenico – 5.5
WooCommerce Amazon Pay<https://woocommerce.com/products/pay-with-amazon/>               by WooCommerce – 2.0.3
WooCommerce Notification Premium<http://villatheme.com/>                by Andy Ha (villatheme.com) – 1.4.2.3
WooCommerce Order Status Manager<http://www.woocommerce.com/products/woocommerce-order-status-manager/>         by SkyVerge – 1.13.2
WooCommerce Payments<https://woocommerce.com/payments/>         by Automattic – 2.6.1
WooCommerce PayPal Payments<https://woocommerce.com/products/woocommerce-paypal-payments/>              by WooCommerce – 1.3.2
WooCommerce Product Add-ons<https://woocommerce.com/products/product-add-ons/>          by WooCommerce – 4.1.0
WooCommerce Shipping & Tax<https://woocommerce.com/>            by WooCommerce – 1.25.15
WooCommerce Shipment Tracking<https://woocommerce.com/products/shipment-tracking/>              by WooCommerce – 1.6.27
WooCommerce USPS Shipping<https://woocommerce.com/products/usps-shipping-method/>               by WooCommerce – 4.4.55
WooCommerce Smart Coupons<https://woocommerce.com/products/smart-coupons/>              by StoreApps – 4.24.0
WooCommerce<https://woocommerce.com/>           by Automattic – 5.4.1
Wordfence Security<http://www.wordfence.com/>           by Wordfence – 7.5.4
Yoast SEO Premium<https://yoa.st/2jc>           by Team Yoast – 16.6
Yoast SEO<https://yoa.st/1uj>           by Team Yoast – 16.6.1
WP-Optimize Premium - Clean, Compress, Cache<https://getwpo.com/>               by David Anderson, Ruhani Rabin, Team Updraft – 3.1.11
Smush Pro<http://wpmudev.com/project/wp-smush-pro/>             by WPMU DEV – 3.8.7
WPMU DEV Dashboard<https://wpmudev.com/project/wpmu-dev-dashboard/>             by WPMU DEV – 4.11.1
Yoast SEO: WooCommerce<https://yoast.com/wordpress/plugins/yoast-woocommerce-seo/>              by Team Yoast – 14.1
WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels (Pro)<https://www.webtoffee.com/product/woocommerce-pdf-invoices-packing-slips/>              by WebToffee – 4.1.9
YITH WooCommerce Badge Management Premium<https://yithemes.com/themes/plugins/yith-woocommerce-badges-management/>              by YITH – 1.4.14
YITH WooCommerce Wishlist Premium<https://yithemes.com/themes/plugins/yith-woocommerce-wishlist/>               by YITH – 3.0.23

Your Designer,
Wayne Hesler-Mondore
________________________________
***@***.***

22 Monticello Street, Richfield Springs, NY 13439<https://maps.google.com/?q=22+Monticello+Street,+Richfield+Springs,+NY+13439&entry=gmail&source=g>
V: 315.527.3090  F: 800.732.3617
________________________________
Online Ordering and Gift Catalog at hmprintdesign.com<https://hmprintdesign.com/>
Follow us on: Facebook <https://facebook.com/hmprintdesign> | Pinterest <https://pinterest.com/hmprintdesign> | Twitter<https://twitter.com/hmprintdesign> | Instagram<https://instagram.com/hm_print_and_design>
________________________________
PLEASE READ IMPORTANT INFORMATION ABOUT THIS EMAIL:
All info contained in this e-mail is meant for the person sent to, please notify us if this is NOT you.
All content is copyright of HM Print & Design.
Please check web site for current guidelines, policies and terms<https://hmprintdesign.com/terms>.
HM Print & Design, WayneConcepts, Monticello Mercantile & Mondore-ables are solely operated by Wayne Hesler-Mondore

------ Original Message Sent: (date) ------

**Comment by dans-art** [comment]
Hi Wayne

Thanks
I will look into it asap.

Best, Daniel

**Comment by dans-art** [comment]
Hi Wayne

Please try this Version. Just install it with the Plugin Manager in Wordpress.
This version fixes some bugs and adds a better error reporting.
Please let me know, if this solves your Problem. Otherwise don't hesitate to reach out to me.

Best, Daniel

[add-customer-for-woocommerce-1.1.zip](https://github.com/dans-art/wac-woocommerce-add-customer/files/6772591/add-customer-for-woocommerce-1.1.zip)

**Comment by dans-art** [comment]
Version 1.1 is official released. Please try it out and let me know, if the problem still exists.
Best, Daniel

**Comment by hmprintdesign** [comment]
Seemed to be working. Ty


Wayne Hesler-Mondore

___________________________________

Graphics, Printing, Rustic Décor, Gifts, CNC Woodworking315.527.3090<tel:315.527.3090>

Online Ordering and Gift Catalog at hmprintdesign.com<https://hmprintdesign.com/>

________________________________

**Comment by dans-art** [comment]
Thanks for your feedback. Therefore i close the issue.
